### ISSUE TITLE
Grammatical Issue

### ISSUE THREAD

**Issue by Avyansh0001** [orcsan/orcsan.github.io#7]
Hi,
There is a grammatical mistake on your website as it says **Builded by Orcsan** but it should be *_### *Built by Orcsan_**
![image](https://user-images.githubusercontent.com/75159744/169467843-cd5d7742-c5be-41e5-9a59-c79e59a6ca70.png)

Thanks,
Avyansh Ralph

**Comment by elevenvac** [comment]
thanks.

**Comment by Avyansh0001** [comment]
not a problem... I'm thankful that I helped you
